### ISSUE TITLE
Merge in latest version of swigmake

### ISSUE THREAD

**Issue by iamthad** [rdeits/swig-eigen-numpy#6]
This works with Eigen 3.3 if the swigmake directory is replaced with the contents of your swigmake repo. 

It looks like pull_subs.sh is supposed to automate this process, but it is creating merge conflicts for me.

**Comment by rdeits** [comment]
Yeah, git subtrees has been an endless source of disappointing merge conflicts. I fixed it by just blowing away the folder and adding the subtree again: #7
