### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by chrisfowler** [rdeits/swig-eigen-numpy#8]
Am getting the following error when running 'make' 

```
cueball:build chrisfowler$ cmake .. -DCMAKE_INSTALL_PREFIX=../install
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/chrisfowler/dev/swig-eigen-numpy/build
cueball:build chrisfowler$ make
[ 28%] Built target inverter
[ 57%] Built target testInverter
[ 71%] Building CXX object python/CMakeFiles/_inverterWrapperPython.dir/inverter_wrapperPYTHON_wrap.cxx.o
/Users/chrisfowler/dev/swig-eigen-numpy/build/python/inverter_wrapperPYTHON_wrap.cxx:4780:12: error: explicit specialization of non-template struct
      'traits_reserve'
    struct traits_reserve<std::vector<T> > {
           ^             ~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [python/CMakeFiles/_inverterWrapperPython.dir/inverter_wrapperPYTHON_wrap.cxx.o] Error 1
make[1]: *** [python/CMakeFiles/_inverterWrapperPython.dir/all] Error 2
make: *** [all] Error 2
cueball:build chrisfowler$
```

Eigen3 was installed automatically and other dependencies installed with 'brew'

Am on Mac Sierra 10.12.6.

Am new to integrating c++ and python so reaching out for any assistance you can give. 

Thankyou

**Comment by rdeits** [comment]
It looks like this project is very sensitive to SWIG version, see https://github.com/RobotLocomotion/drake/issues/4914

By the way, I've switched to PyBind11 for all my Python wrappers and have found it much more reliable than SWIG. You might want to check it out.

**Comment by chrisfowler** [comment]
Yes, I did see that :|

Thank you for quick response and pointer to PyBind11; I'll take a look.
